from langchain_huggingface import ChatHuggingFace,HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel,Field

load_dotenv()

llm = HuggingFaceEndpoint(
    repo_id= "Qwen/Qwen2.5-7B-Instruct",
    task= "text-generation",
    temperature=1.5
)

model = ChatHuggingFace(llm = llm)

class Person(BaseModel):
    name : str = Field(description="Name of the person")
    age : int = Field(gt=18 ,description="Age of the person")
    city : str = Field(description="City of the person where he/she lives")

parser = PydanticOutputParser(pydantic_object=Person)

# Parsing means reading, understanding the structure of the data, and then converting it into a structured form that a program can work with.

template = PromptTemplate(
    template="give the name, age and city of person lived in {country} \n {format_instruction}",
    input_variables=["country"],
    partial_variables={"format_instruction" : parser.get_format_instructions()}
)

# {format_instruction} is a fixed set of instructions generated by the parser to tell the model exactly how to format its response according to the specific format and validation the we apply.so it can be parsed automatically.

chain = template | model | parser

result = chain.invoke({"country" : "Pakistan"})

print(result)